name: docs

on:
  push:
    branches: [develop]
    paths:
      - "docs/**"
      - ".github/mkdocs.yml"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  pages:
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install MkDocs
        run: pip install mkdocs mkdocs-material

      - name: Build site
        run: mkdocs build -f .github/mkdocs.yml --strict

      - uses: actions/configure-pages@v4
        with:
          token: ${{ secrets.PAGES_TOKEN }}
          enablement: true

      - uses: actions/upload-pages-artifact@v3
        with:
          path: .github/site

      - id: deployment
        uses: actions/deploy-pages@v4
