name: docs

on:
  push:
    branches: [develop]
    paths:
      - "docs/**"
      - ".github/mkdocs.yml"
  workflow_dispatch:

permissions:
  contents: read # checkout
  pages: write # upload + deploy
  id-token: write # OIDC token for deployment

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install MkDocs
        run: |
          pip install mkdocs mkdocs-material

      - name: Build site
        run: mkdocs build -f .github/mkdocs.yml --strict # outputs to .github/site

      # ----------------------------------------------------------------
      # Configure (and, if necessary, create) the Pages site.
      # `enablement: true` lets the action create the site the first time,
      # which eliminates any race with the Terraform job.
      # ----------------------------------------------------------------
      - name: Configure Pages
        uses: actions/configure-pages@v4
        with:
          enablement: true # create or verify Pages, build_type=workflow

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .github/site # matches build output

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
