name: Deploy Docs

on:
  push:
    branches: [main]
    paths:
      - "docs/**"
      - ".github/mkdocs.yml"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install MkDocs & Material Theme
        run: |
          pip install mkdocs mkdocs-material

      - name: Deploy to GitHub Pages
        run: |
          mkdocs gh-deploy -f .github/mkdocs.yml --force
