# Publishes container images for:
#   • every merge to `develop`  →  ghcr.io/<org>/<repo>:develop
#   • every semver tag          →  ghcr.io/<org>/<repo>:<tag>  (+ :latest)
#
name: publish

on:
  push:
    branches: [develop]
    tags: ["v*.*.*"]

permissions:
  contents: write
  packages: write

env:
  IMAGE_NAME: ${{ github.repository }}

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: vars
        run: |
          if [ "${GITHUB_REF_TYPE}" = "tag" ]; then
            echo "TAG=${GITHUB_REF_NAME}"   >>"$GITHUB_OUTPUT"
            echo "EXTRA=latest"            >>"$GITHUB_OUTPUT"
          else
            echo "TAG=develop"             >>"$GITHUB_OUTPUT"
            echo "EXTRA="                  >>"$GITHUB_OUTPUT"
          fi

      - name: Build and push
        run: |
          IMAGE=$(echo "ghcr.io/${{ env.IMAGE_NAME }}" | tr '[:upper:]' '[:lower:]')
          docker build -f docker/Dockerfile -t "$IMAGE:${{ steps.vars.outputs.TAG }}" .
          docker push "$IMAGE:${{ steps.vars.outputs.TAG }}"

          if [ -n "${{ steps.vars.outputs.EXTRA }}" ]; then
            docker tag  "$IMAGE:${{ steps.vars.outputs.TAG }}" "$IMAGE:${{ steps.vars.outputs.EXTRA }}"
            docker push "$IMAGE:${{ steps.vars.outputs.EXTRA }}"
          fi
