name: Publish Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup environment
        run: make setup

      - name: Build
        run: make build

      - name: Package artifacts
        run: make package

      - name: Extract tag
        id: get-tag
        run: echo "tag=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT

      - name: Docker login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push versioned image
        run: |
          IMAGE=ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}
          docker build -t $IMAGE:${{ steps.get-tag.outputs.tag }} -t $IMAGE:latest .
          docker push $IMAGE:${{ steps.get-tag.outputs.tag }}
          docker push $IMAGE:latest

      - name: Attach artifacts to release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
